### ISSUE TITLE
Auto Restarting for Airlock

### ISSUE THREAD

**Issue by ApolloX939** [Droog71/moontest#6]
Could we expand the Airlock so it has say 2 or more blocks so we could automate it to auto fix when it fails (but not when it's open).

> Not really a big deal since once a fully automated base is build the user can just about AFK since everything auto restarts. (Just needs to keep the drill going to keep that cash flow coming in)

Not that this is really needed, since once a base is fully automated it's the only thing that needs to be "fixed" and re-closed.

**Comment by Droog71** [comment]
I thought about adding mesecons support for the airlock but never got around to it. 

Maybe instead of compatibility with sensors and relays, I could add the option of running a long wire from the airlock back to the reactor area so you can just press a button and close it from a distance.

There is a terraforming machine in the game now. Once you have it running, you can leave the airlock open because oxygen and heat are no longer required. This doesn't happen until late in the game though.

**Comment by ApolloX939** [comment]
Cool, can't wait to try the new version.

> I will update my copy so the PR will be up to date adding a better way to execute all those dofile commands.
