### ISSUE TITLE
Bug: Using Mesecons wire to kill aliens

### ISSUE THREAD

**Issue by ApolloX939** [Droog71/moontest#7]
I'm not sure why but if you placed a strip of wires in the front of the airlock it forms almost a force field (Prevents aliens from entering the habitat while letting the player thru with no issues)

![screenshot_20220109_180107](https://user-images.githubusercontent.com/20930999/148704784-fb6dc421-cbae-4279-8d97-b31e54b46d76.png)

> And yes, that is a auto restart circuit for the drill. (Which makes my entire base auto restarting)

**Comment by ApolloX939** [comment]
Ah, so if the alien jumps over it then it's still alive, but if not then it oddly vanishes (I don't think you get anything from it, think a environmental effect)

### Environmental effects/conditions

Actually when I typed the above I realized that could be the next thing...

* An Ion Storm or even Solar Radiation which increases the chance things can fail for a period of time then goes away.

> So far all I've come up with is Solar Radiation (which is a real issue in space, the moon has no atmosphere to reduce that effect), though most of the real stuff we have in space comes with protective shielding.

But these effects would make the game change from earn X thousand money to "win" to more of a survive as long as you can. (possibly make it so the map can be reset, but players could earn awards for surviving X days or killing X aliens (etc.) which unlocks cool starting/in-game bonus content. (A good starting award could be complete the tutorial, or even first played the game, survived one day)

> Not to mention these effects should be applied every X days (14 or more days, but lasts at most 2-3 days).

**Comment by Droog71** [comment]
I also came across this bug with the mesecons wires killing the aliens. It was pretty confusing at first.  In the end, I removed the check for air nodes entirely. It was originally added due to another bug with colliders that was fixed a long time ago, so not necessary anymore.

I like the solar radiation idea. I like the awards idea also. The [awards](https://content.minetest.net/packages/rubenwardy/awards/) mod could be used for this which would save a lot of work.

`...change from earn X thousand money to "win" to more of a survive as long as you can.`

The new end game is different in version 1.0.4. The end goal is no longer to earn a lot of money but to generate enough power to install a terraforming machine that turns the moon into a habitable place. You can keep playing after that but that is the biggest achievement at the moment.

**Comment by ApolloX939** [comment]
Yeah I fixed this in my PR but I guess I should remove my fix so it's more inline with the original now.

> I kind of thought that was why it was in there, but yeah now it's not needed.

Still got to play the new version. :)

**Comment by ApolloX939** [comment]
Todo:

- [x] Look at the PR and possibly merge it. (It's not that important but it can save a lot of typing, and prevents miss typing stuff)
- [x] Close this issue, since it sounds like the issue is fixed.
